services:
  danjam-mysql:
    container_name: danjam-mysql
    image: kimdohee58/danjam-mysql:latest  # 원하는 MySQL 버전을 사용
    volumes:
      - mysql-data-danjam:/var/lib/mysql  # 데이터를 호스트에 저장
    environment:
      MYSQL_DATABASE: danjamdb  # 기본 데이터베이스 설정
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: danjam1234  # MySQL 루트 비밀번호 설정
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - "3306:3306"  # MySQL 포트 매핑
    networks:
      - danjam-network

  danjam-service:
    build: .  # 현재 디렉터리에서 Dockerfile을 사용해 빌드
    container_name: danjam-service
    image: kimdohee58/danjam-service:latest
    ports:
      - "9010:9010"  # 호스트와 컨테이너의 포트를 매핑
    environment:
      DB_HOST: danjam-mysql  # MySQL 호스트 이름 설정 (서비스 이름과 동일하게)
    depends_on:
      - danjam-mysql
    command: >
      sh -c "
        until nc -z -v -w30 danjam-mysql 3306; do
          echo 'Waiting for MySQL...';
          sleep 5;
        done;
        java -jar /danjam-service.jar
      "
    networks:
      - danjam-network
    volumes:
      - .:/back-main  # 애플리케이션 소스와 데이터를 컨테이너와 동기화

volumes:
  mysql-data-danjam:  # MySQL 데이터 저장소

networks:
  danjam-network:
    driver: bridge